### ISSUE TITLE
No CI on pull requests?

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#1005]
Tests are not executed anymore on PR. Is it a bug or "a feature" 🤔 ?

**Comment by composerinteralia** [comment]
That is definitely a bug. I see no sign of builds for your branches on Travis, but I have no idea why. 

Thanks for all your contributions!

**Comment by composerinteralia** [comment]
It looks like we had only "Build pushed branches" checked and not "Build pushed pull requests". I am going to see what happens if I check both of those instead. Could you try pushing an additional commit (or amending a commit and force pushing)  to one of your branches to see if it triggers a build now?

**Comment by composerinteralia** [comment]
Ah, I see now on the requests page that your branches failed to start building with the message "Build type disabled via repository settings (pull_request)". That makes me think toggling the PR setting was the right thing to do here.

**Comment by delphaber** [comment]
> Could you try pushing an additional commit (or amending a commit and force pushing) to one of your branches to see if it triggers a build now?

Sure! Thanks for the support!

**Comment by delphaber** [comment]
They run! Thank you :) Sadly, all of my PR is failing :D But I created a new PR to fix (I think) master :)
