### ISSUE TITLE
Multiple gems that are mentioned in the ReadMe are not installed.

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/suspenders#1046]
Using Suspenders (version: 1.54.1), I ran `suspenders app --heroku true` but it didn't install numerous gem that are mentioned in the readme (ex: delayed_job, bullet, and bourbon). 

The Gemfile that Suspenders generated:

    source "https://rubygems.org"

    git_source(:github) do |repo_name|
      repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
      "https://github.com/#{repo_name}.git"
    end

    ruby "2.6.6"

    gem "autoprefixer-rails"

    gem "bootsnap", require: false
    gem "honeybadger"
    gem "pg"
    gem "puma"
    gem "rack-canonical-host"
    gem "rails", "~> 6.0.0"
    gem "recipient_interceptor"
    gem "sassc-rails"
    gem "skylight"
    gem "sprockets", "< 4"
    gem "title"
    gem "tzinfo-data", platforms: [:mingw, :x64_mingw, :mswin, :jruby]
    gem "webpacker"

    group :development do
      gem "listen"
      gem "web-console"
    end

    group :development, :test do
      gem "awesome_print"
      gem "pry-byebug"
      gem "pry-rails"
    end

    group :test do
      gem "formulaic"
      gem "launchy"
      gem "timecop"
      gem "webmock"
    end

    gem "suspenders", group: [:development, :test]

**Comment by composerinteralia** [comment]
I ran `suspenders app --heroku true` with v1.54.1 and I ended up with a Gemfile that did include the specific gems you mentioned. I am guessing something failed along the way and caused a bunch of the generators to fail (this has been an ongoing problem. Hopefully as we [move toward suspenders being a library of generators](https://github.com/thoughtbot/suspenders/blob/master/GOALS.md) this problem will be mitigated to some extend because folks will be running one generator at a time rather than the full app generator). Could you share the output you got from running `suspenders`? There is likely an error message buried in there somewhere.

**Comment by thiagoa** [comment]
@ACPK Thank you for reporting this issue! I'm closing it in favor of:

https://github.com/thoughtbot/suspenders/issues/1080
