### ISSUE TITLE
In a freshly generated application there is no rspec

### ISSUE THREAD

**Issue by fuzzygroup** [thoughtbot/suspenders#1097]
rails g controller Home
W, [2022-06-19T06:31:29.100005 #26381]  WARN -- Skylight: [SKYLIGHT] [5.3.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
      create  app/controllers/home_controller.rb
      invoke  erb
      create    app/views/home
       error  rspec [not found]
      invoke  assets
      invoke    scss

Grep against Gemfile:

❯ cat Gemfile | grep rails
gem "autoprefixer-rails"
gem "rails", "~> 6.0.0"
gem "sassc-rails"
  gem "pry-rails"

❯ cat Gemfile | grep rspec

(nothing was found)

**Comment by thiagoa** [comment]
@fuzzygroup Thank you for reporting this issue! It has been fixed with the latest release:

https://github.com/thoughtbot/suspenders/releases/tag/v1.56.0

It happened because when something failed along the way Suspenders wouldn't abort and would keep running, giving the illusion that the app was generated without problems. Please try out v1.56.0 and feel free to reopen this issue if you find any problems.
