### ISSUE TITLE
Best practice for updating Suspenders and an app utilising it?

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/suspenders#503]
Hi guys,

I've recently started using suspenders but have found that some aspects either don't work or are being changed frequently (e.g. flashes issues, refills line heights, Unicorn/Puma changes).

I was wondering if you could add a brief section to the readme that advises on the process that should be taken to upgrade suspenders and a project that is already using it? It would be quite helpful I think.

Cheers,

Rikki

**Comment by croaky** [comment]
Hi @rikkipitt, sorry for the recent issues. It's pretty rare that we've had breakages like this. I believe both the flashes and refilles line heights can be fixed in your repo by making your `Gemfile` line for Refills be `gem "refills", github: "thoughtbot/refills"`. I'm trying this now and intend to open a pull request once tested.

Suspenders is only a generator, so the only time to really update it is right before you're ready to create a new project.

In the old days, Suspenders used to have a rake task something like `rake suspenders:pull` (the pun was part of the reason for the name). That worked because it was a repo of files that could be Git pulled and you'd just resolve Git conflicts normally locally.

Over time, a few factors led us to not go that route anymore:

* Use Rails templates so we don't have to keep copying Rails-generated files into Suspenders, instead having Suspenders run `rails new` and then making its alterations
* Wanting to add a few flags so there are a few different options for the most typical starting points we have for projects.

So, the best way to be up to date is to "watch" the Suspenders repo and decide whether you want to make any of the same changes in your repo.

Hope that helps.

**Comment by mjankowski** [comment]
RE: "updating", I would add -- it does in fact work to re-run `suspenders` on an already created project.

It will prompt you about what to overwrite or not, and you can decide how much you want to change.

I usually hit `a` to tell it to overwrite everything, and then use git to back in and out of whatever I actually want to update in the project.

**Comment by rikkipitt** [comment]
Hi @croaky and @mjankowski - thank you very much for your input, it's really appreciated. Keep up the great work and I'll keep and eye on your repo for changes and updates as they happen.

Best,

Rikki
