### ISSUE TITLE
Nitrous.io

### ISSUE THREAD

**Issue by lawgixlaw** [thoughtbot/suspenders#547]
Got an error that suspenders requires Ruby 2.2.1.  That's the version that's installed and running in the Nitrous box by default.  Any ideas?

**Comment by mrlee-io** [comment]
A nitrous.io box, by default, is running ruby 2.1.1p76 ( I just started a new rails box ).

In order to install a different version you use what they call 'parts'.

```
parts search ruby
parts install xyz
```
Restart the console and you should be good to go with whatever version you installed.

note 1:  They do not currently have a 'part' for ruby 2.2.1
note 2:  You can also use the GUI to manage packages under 'autoparts'.
note 3:  If you can't wait for nitrous to release 2.2.1 you can try downloading suspenders and building it manually requiring only 2.2.0 (no idea if it will build)

**Comment by tute** [comment]
Suspenders should be more permissive with it's ruby version for generating apps I think. A user should be able to use "good" Ruby versions without the need for services to be all running latest Ruby (while still generating apps that require the latest version available, as a good default).

**Comment by lawgixlaw** [comment]
I'm a beginner at this.   What you're saying is that I can't use suspenders on Nitrous.io until they launch Ruby 2.2.1, correct?  

I work on a Chromebook and am really liking the idea of developing completely in the cloud between Nitrous and Heroku.   Suspenders looks like a good way for me to build apps by piecing together code parts that others have written for much of the basic stuff like user accounts, etc.   

Am I right in that assumption?   Is there another gem or tool that would do the same thing as suspenders?

**Comment by tute** [comment]
If @jferris doesn't disagree, I'll relax the Ruby Version needed for suspenders gem to >= 2.1.

**Comment by tute** [comment]
Closing in favor of PR. Thanks for your input, I understand your issue.
