### ISSUE TITLE
Which port should foreman be running on?

### ISSUE THREAD

**Issue by LimeBlast** [thoughtbot/suspenders#602]
I'm sorry if this is a silly question, or if I've misunderstood something, but there seems to be some conflicting defaults in the port configuration for foreman/running the dev server.

According to the `.foreman` file, the port should be `7000`, but looking in the `config/environments/developments.rb` file, it suggests a port of 5000, and further still, the default port setting for `HOST` and `ASSET_HOST` in `.sample.env` is 3000.

Should these not all be the same?

**Comment by tute** [comment]
It looks like suspenders build with random ports, but `.sample.env` fixes the Rails default of 3000.

```
./lib/suspenders/app_builder.rb:      @port ||= [3000, 4000, 5000, 7000, 8000, 9000].sample
./templates/sample.env:ASSET_HOST=localhost:3000
```

Random port was introduced in https://github.com/thoughtbot/suspenders/commit/4caa6123 by @croaky, to be able to run multiple suspenders apps with foreman without conflicts. Now that array has 6 elements (which are random anyway), so this doesn't seem like a reliable solution. Also, I personally don't encounter that problem because I typically load two Rails apps at most simultaneously.

I wouldn't mind suspenders defaulting to 3000, but let's see what other users think. I wouldn't mind using the 3000-3100 range ([Chrome considers 6000 unsafe](https://github.com/thoughtbot/suspenders/commit/208a6f09)), and making `.sample.env` smart about the random selection.

**Comment by LimeBlast** [comment]
For now, I've changed all of mine to 3000 (just because that's what I'm used to). If you did stick with a random port, would it be worth making sure the `HOST` and `ASSET_HOST` get set to the same, and maybe update `config/environments/development.rb` to use:

      config.action_mailer.default_url_options = { host: ENV.fetch("HOST") }

:)

**Comment by tute** [comment]
Absolutely. I expected `action_mailer` to already read the proper host, but there might be a bug,

**Comment by LimeBlast** [comment]
:+1:

**Comment by tute** [comment]
Thanks! Closing in favor of PR: https://github.com/thoughtbot/suspenders/pull/588
