### ISSUE TITLE
Instructions for non-optional configuration

### ISSUE THREAD

**Issue by klaaspieter** [thoughtbot/suspenders#746]
I just deployed my first suspenders app and was first greeted by an SMTP configuration error. After removing the SMTP config, I received error: `KeyError: key not found: "APPLICATION_HOST"`. 

In #532 @tute mentioned suspenders is not meant to be plug and play. Does it make sense to add something to the README or after suspenders finishes to explain what still needs configuring?

**Comment by tute** [comment]
We've been documenting through exceptions until now, which feels very unnatural to me. In https://github.com/thoughtbot/suspenders/pull/722#issuecomment-210556755 I state that I wish for a suspended app not to fail upon deploy to Heroku, but I've had some pushback in moving towards that direction.

Specifically for this case, your PR fixes the `APPLICATION_HOST` issue (thank you!). `SMTP` could be conditional or not, but if we don't make it so, I vote for having what's needed in the README.

**Comment by mike-burns** [comment]
Uses for `APPLICATION_HOST`:

- Used in `Rack::CanonicalHost`. This way, requests to other hostnames (such as the Heroku hostname) will redirect. This helps with TLS certs, SEO, and other problems.
- Used as the default `config.action_controller.asset_host`, though can be overridden by setting `ASSET_HOST`. This value is used in e.g. `image_url`, `stylesheet_link_tag`, etc. This ensures that it makes the request using the canonical hostname, which helps with TLS and browser security checks.
- Used as the production `Action::Mailer` host. This way emails will appear to come from the correct domain, which helps ensure reliable delivery.

^ This might all be useful for writing documentation on this.

**Comment by tute** [comment]
`APPLICATION_HOST` is now fixed, `SMTP` variables are next (failing tests in https://github.com/thoughtbot/suspenders/pull/722 are targeting that).

I'm not sure what variables will fail next, but I do plan to move #722 forward, which leads to fixing this issue.

If in the end we get green CI in different environments, but developer input is still needed (for example, SMTP credentials), then I'll add post-generate instructions so that developers know what to expect.

Thank you all for your input.
