### ISSUE TITLE
Heroku CI fails because DATABASE_URL is set

### ISSUE THREAD

**Issue by johannesschirrmeister** [thoughtbot/suspenders#872]
Hi,

I just enabled Heroku CI for a project I recently created using suspenders. Unfortunately, I couldn't run the tests successfully due to the following line: `abort("DATABASE_URL environment variable is set") if ENV["DATABASE_URL"]` in https://github.com/thoughtbot/suspenders/blob/master/templates/rails_helper.rb#L4

It seems that the heroku-postgresql add-on is added to the Heroku CI app, causing the DATABASE_URL variable to be set. I'm not aware of any configuration changes I have made so I'm assuming the fact that this add-on is installed is a result of "normal" suspenders usage.

I'm puzzled that this hasn't been reported before as this line has been there for a while. Why shouldn't I use a DB provided by Heroku in my test environment? And why was it configured automatically anyways?

Cheers,
Johannes

PS: If nothing else comes out of this, I will propose a change to the abort message. It was very hard to spot "DATABASE_URL is set" as the error cause.

**Comment by mike-burns** [comment]
From the PR that added it: https://github.com/thoughtbot/suspenders/pull/601#issuecomment-131845392

> Rails 5 is going to address this issue, but in the meantime we could raise if DATABASE_URL is set at all.

@derekprior can you speak more to how Rails 5 addresses this? Can we remove this hack?

**Comment by derekprior** [comment]
I believe the comment was mistaken, unfortunately. 

Rails 5 added limited environment protection so you can't run `rake db:drop` or other destructive rake tasks without something equivalent to `ENABLE_FOOT_GUN=1 rake db:drop` (not the actual env variable, but you get the point).

My hope at the time of that comment was that the solution introduced in Rails 5 would also cover database cleaner, but it does not.

We could maintain the spirit of this check by asserting `ActiveRecord::InternalMetadata[:environment] == 'test'` instead of checking `database_url`, I think. it's also worth considering if we would need this protection at all if we got rid of database cleaner?

**Comment by mike-burns** [comment]
Maybe we should revisit the standard `rails_helper.rb` from RSpec, e.g. https://github.com/rspec/rspec-rails/pull/1383

**Comment by gerryhd** [comment]
So... was this fixed? Will this be fixed? Does anyone have a workaround, or is it safe to just comment out that line? It's odd to claim this works with Heroku out of the box but make CI tests fail due to that line in the rails_helper.rb file.

**Comment by nickcharlton** [comment]
I had to make a similar change on another project recently, so I've opened #979 which should help solve this. It takes the same approach as `rspec-rails` and what was suggested above.

**Comment by thiagoa** [comment]
It looks like this issue was already resolved by @nickcharlton so I'm closing it ❤️
