### ISSUE TITLE
Breaking change to Rack::Timeout causes Heroku deployment failure

### ISSUE THREAD

**Issue by orenyk** [thoughtbot/suspenders#918]
See [here](https://github.com/heroku/rack-timeout/issues/130) for more info. It looks like we can just update [this file](https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/generators/production/timeout_generator.rb) - I can try to open up a PR later tonight. Thanks!

**Comment by orenyk** [comment]
Based on the README it seems like the recommended way to modify the timeout is now through environment variables. Two questions:

1. Would adding the environment variable (`RACK_TIMEOUT_SERVICE_TIMEOUT`) to the `.env` template with a default value of 10 be sufficient to match the current Suspenders functionality?
2. Out of curiosity, is there a reason why you prefer 10 seconds to the default of 15?

**Comment by composerinteralia** [comment]
Hey Oren, nice to see you again (we met at the last RailsConf). I would be happy to help you get this through. Are you ready to make a PR, or would you like any help?

**Comment by toobulkeh** [comment]
I would suggest just using the new defaults for Rack::Timeout, as the new config would require all 4 variables to be set to `10`, since Heroku just broke them out:

https://github.com/heroku/rack-timeout/blob/master/README.md#configuring

Rack::Timeout takes the following settings, shown here with their default values and associated environment variables.
```
service_timeout:   15     # RACK_TIMEOUT_SERVICE_TIMEOUT
wait_timeout:      30     # RACK_TIMEOUT_WAIT_TIMEOUT
wait_overtime:     60     # RACK_TIMEOUT_WAIT_OVERTIME
service_past_wait: false  # RACK_TIMEOUT_SERVICE_PAST_WAIT
```

These settings can be overriden during middleware initialization or environment variables RACK_TIMEOUT_* mentioned above. Middleware parameters take precedence:

`use Rack::Timeout, service_timeout: 5, wait_timeout: false`

**Comment by orenyk** [comment]
@composerinteralia great to hear from you and congrats on the new gig 😄! I'm happy to open a PR - I just wanted to make sure my approach above made sense.

To @toobulkeh's point, it looks like the old `Rack::Timeout.timeout=` method set the `service_timeout` attribute, so that was the only thing changed in the old Suspenders config and we can easily replicate that in our `.env` file.

I'll throw a PR up and we can move this discussion there. Thanks!
