### ISSUE TITLE
"DATABASE_URL environment variable is set" is not a helpful error message

### ISSUE THREAD

**Issue by halogenandtoast** [thoughtbot/suspenders#921]
Howdy tb folks,

Ran into an issue where I was trying to debug an application for someone that was experiencing this error message. Unfortunately it's quite a vague error message and doesn't really explain why having this value is set. It might be useful to explain why this is bad, or link to some documentation.

If you have a preference on either making the error message longer to provider more detail (my preferred approach) or linking to some documentation, let me know and I can try to make a PR to update it it.

- Goose

**Comment by toobulkeh** [comment]
Here is the line in question. https://github.com/thoughtbot/suspenders/blob/master/templates/rails_helper.rb#L4

Which came from: https://github.com/thoughtbot/suspenders/commit/2c069e1e387e3a538aa44a2d235f05e22b0cb03a

In short, DATABASE_URL should never be set, because it can be accidentally pulled from production, meaning your local commands or testing might override a remote database.

The correct course of action is to delete that env variable and not reference production locally.

**Comment by halogenandtoast** [comment]
This isn't the case for Heroku CI which is where this is necessary because the environment variable is how we communicate the location of their database add-on and the error message is vague enough that it confuses customers.

**Comment by mike-burns** [comment]
How about checking whether `ENV['CI']` is set as part of the conditional?

**Comment by thiagoa** [comment]
We can close this ticket because that exception no longer exists:

https://github.com/thoughtbot/suspenders/pull/979/files

Thank you @halogenandtoast for reporting this! ❤️
