### ISSUE TITLE
Rspec failing

### ISSUE THREAD

**Issue by lpender** [thoughtbot/suspenders#955]
Writing a simple feature test to start with:

*spec/features/user-sees-homepage_spec.rb*
```
feature 'User sees homepage' do
  scenario 'and it works' do
    visit "/"
  end
end
```

Leads to the following error (partial trace):

```
$ bundle exec rspec
```
```
NoMethodError:
  undefined method `feature' for main:Object
# ./spec/features/user-sees-homepage_spec.rb:1:in `<main>'
# -e:1:in `<main>'
Run options: include {:locations=>{"./spec/features/user-sees-homepage_spec.rb"=>[3]}}

All examples were filtered out
```

**Comment by mike-burns** [comment]
Do you need to `require "rails_helper"`?

**Comment by lpender** [comment]
Yes, that fixed it!

Any idea if this is intentionally not included in `spec_helper` or mentioned in the `README`?

Happy to open a PR if not.

Thanks

**Comment by mike-burns** [comment]
It looks like this is intentionally separate from `spec_helper`: 936dcc70e49a5aa61667e17442f1d7ca6ed30582.

The difference is that `spec_helper` is the minimum needed to run the tests, and `rails_helper` is for anything that actually needs Rails. So for unit testing your service object `spec_helper` should do, but for feature testing you need `rails_helper`.

It'd be great to document this somewhere! The README seems great for that. Thank you!

**Comment by lpender** [comment]
Looks like the referenced commit is from 2014, and the upgrade note is from 2016, so it makes sense that this has stopped working.

Would make sense not to require it if it was going to be unnecessary for some significant percentage of users, for example if some people wanted to use Suspenders to build another type of Ruby app other than Rails.

However,

"Suspenders is the base _Rails_ application used at thoughtbot."

Since this is a Rails application template, and 100% of the applications generated with it will be running on Rails, I don't see any reason to be shy about requiring the `rails_helper`.

It looks like the pertinent code which includes `spec_helper` was written in 2014, and `rspec-rails` separated that file into two parts in 2016. 

To me it makes sense to include them both by default...

**Comment by mike-burns** [comment]
You are right that the majority of our tests use `rails_helper`. However, we often only use `spec_helper` for tests under `spec/lib`. We do this to help with performance, since not loading Rails causes the test to be noticeably faster.

Because of this, we intend to keep the division, and to only load `rails_helper` manually.

Is there something we can do to make this easier?

**Comment by thiagoa** [comment]
I agree, when writing feature tests we need to require `rails_helper.rb` instead of `spec_helper.rb`, since this is a Rails application template.

I'm closing this ticket because we did not come to a definitive resolution. If we feel like we should include explicit instructions for when to use `spec_helper.rb` or `rails_helper.rb` in the README, we can still do it and reopen this ticket. But we should also ask the question about whether we should document something that could (probably) be learned from reading the `rspec-rails` docs, or could easily change without advice.

Thank you @lpender for reporting this ❤️
