### ISSUE TITLE
Can't have both browserslist and .browserslistrc

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/suspenders#993]
suspenders generates a [browserslist](https://github.com/thoughtbot/suspenders/blob/master/templates/browserslist) and rails 6 with webpacker generates a [.browserslistrc](https://github.com/rails/webpacker/blob/master/lib/install/config/.browserslistrc).

Having both of these causes `bin/webpack` to fail, so we need to choose one or the other.

@tysongach thoughts?

**Comment by tysongach** [comment]
The `templates/browserslist` file was originally added in https://github.com/thoughtbot/suspenders/commit/7df323348714f7495bd296d8f3ae18baf89d8852 to specify our desired browser support for [Autoprefixer Rails](https://github.com/ai/autoprefixer-rails).

According to their readme:

> If you need to specify browsers for your Rails project, you can save them to `.browserslistrc` and place it under app/assets/stylesheets/ or any of its ancestor directories

So that seems to confirm that we should be fine leveraging `.browserslistrc` going forward.

Interesting detail: [This commit](https://github.com/ai/autoprefixer-rails/commit/f97dab9bb74af9d202723d606bef2b1c0d5371f8) in May 2019 changed that line of documentation to mention `.browserslistrc`, so perhaps they have landed on that given Rails 6's imminent release.
